# Generated by Django 4.2 on 2024-01-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guns',
            new_name='Gun',
        ),
    ]
