# Generated by Django 5.0.1 on 2024-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='calorie_goal',
            field=models.IntegerField(default=0),
        ),
    ]
