# Generated by Django 4.2 on 2024-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classes_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
    ]
