# Generated by Django 4.2 on 2024-01-17 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_subjectreport_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subjectreport',
            name='time',
        ),
        migrations.AddField(
            model_name='subject',
            name='curr_status',
            field=models.CharField(default='No ongoing classes', max_length=200),
        ),
        migrations.AddField(
            model_name='subjectreport',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
