# Generated by Django 4.2 on 2024-01-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='percentage',
            field=models.FloatField(default=100),
        ),
    ]
