# Generated by Django 4.2 on 2024-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
    ]
