# Generated by Django 4.2 on 2024-01-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_item_price_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='item_price',
        ),
    ]
