# Generated by Django 4.2 on 2024-01-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_price_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.happyeater.com/images/default-food-image.jpg', max_length=500),
        ),
    ]
